### ISSUE TITLE
Authentication error on 0.1.3-0.1.4 beta releases for Iguana wallet GUI

### ISSUE THREAD

**Issue by imboogieman** [SuperNETorg/Agama#16] opened 2017-02-03 15:12 UTC
**How to reproduce:**

I run Iguana (0.13-0.1.4)
I open the wallet GUI index.html in Chrome
I create an account
I add KMD in lite mode
I see the message the coin is added
And then I see the authentication error message
And I can not proceed any further.

Though the bug is missing on 0.1.1-0.1.2

**Comment by satindergrewal** [comment] 2017-02-08 16:44
## Possible fix

#### For windows:
1. Close App
2. Open Task Manager
3. Look for processes with name **Electron.exe** and **iguana.exe**
4. If found kill these processes
5. Once sure, processes are killed, open app again. should be working.

#### For OS X:
1. close app
2. Open Terminal
3. run these commands

`ps aux | grep iguana`
the above will show either 1 line output or more

4. if more execute this one:
`pkill iguana`

this will kill the existing backend iguana daemon, which for some reason wasn't killed in previous app exit. due to which you are getting that error and not able to login. this issue will be fixed in next beta build.

5. check again if iguana is still running
`ps aux | grep iguana`

if single line in return, good, otherwise just exeucte `pkill iguana` again.

6. after confirmed it's killed, now open the app again, and you can do things as usual.


#### For Linux:
`sudo chown -R $USER:$USER $HOME/.pm2/`
`sudo chown -R $USER:$USER $HOME/.iguana/`
`sudo chown -R $USER:$USER $HOME/.config/`

after this start Iguana App by double clicking the desktop shortcut. You must have one there.


If not working, update here.

It's fix will be pushed in next build.

**Closed as completed** 2017-06-01 06:32 UTC
Labels: bug
