### ISSUE TITLE
Agama beta won't load

### ISSUE THREAD

**Issue by SlightlyBearded** [SuperNETorg/Agama#80] opened 2017-03-29 13:39 UTC
So I just uninstalled Iguana and installed Agama and when I try to open it, I get a javascript error and the app won't open...

<img width="422" alt="screen shot 2017-03-29 at 9 37 08 am" src="https://cloud.githubusercontent.com/assets/14926703/24457241/9f0f4aec-1463-11e7-8358-322e2f587bb4.png">

**Comment by satindergrewal** [comment] 2017-03-29 13:55
Duplicate of https://github.com/SuperNETorg/Agama/issues/74

**Closed as completed by satindergrewal** 2017-03-29 13:55 UTC
