### ISSUE TITLE
Agama.app crashes  on launch

### ISSUE THREAD

**Issue by danielchalef** [SuperNETorg/Agama#79] opened 2017-03-29 03:52 UTC
Agama Desktop 0.1.6.1e on MacOS 10.12.3 (16D32) crashes on launch. Fresh install using bitrock installer.

See screenshot below.

![Screenshot of crash dialog](https://cloud.githubusercontent.com/assets/131175/24437836/48f1445a-13f8-11e7-9494-de911189c71d.png)

**Comment by satindergrewal** [comment] 2017-03-29 05:41
duplicate of https://github.com/SuperNETorg/Agama/issues/74

**Closed as completed by satindergrewal** 2017-03-29 05:41 UTC
